version: '3.7'
services:

  activemq:
    container_name: activemq
    image: codingpuss/activemq:5.17.2-jre-19-alpine
    ports:
      - 8161:8161
      - 61616:61616
    networks:
      - app-network     
  proxy:
    build: ./reverseproxy
    ports:
      - "80:80"
    networks:
      - app-network

  # Port 8081
  userservice:
    build: backend_java/ms-user
    networks:
      - app-network

  # Port 8082
  authservice:
    build: backend_nodeJs/ms-auth
    networks:
      - app-network

  # Port 8083
  cardbasicservice:
    build: backend_java/ms-cardbasic
    networks:
      - app-network

  # Port 8084
  storeservice:
    build: backend_java/ms-store/ms-store
    networks:
      - app-network

  # Port 8085
  cardservice:
    build: backend_java/ms-card
    networks:
      - app-network

  # Port 8086
  chathistoryservice:
    build: backend_java/ms-chathistory
    networks:
      - app-network

  # Port 8087
  # gameservice:
  #   build: ./backend_nodeJs/ms-game
  #   networks:
  #     - app-network

  # Port 8088
  logesbservice:
    build: ./backend_java/ms-logesb
    networks:
      - app-network

  # notificationservice:
  #   build: .backend_java/MS-Notification
  #   networks:
  #     - app-network

  client:
    build: ./client
    networks:
      - app-network



networks:
  app-network: