name: ASI CICD
on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true  
jobs:

  push-ms-card:
    runs-on: ubuntu-latest
    env:
      working-directory: ./backend_java/ms-card 
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Login to DockerHub
        run: docker login -u ${{secrets.DOCKERHUB_USERNAME }} -p ${{secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push backend
        uses: docker/build-push-action@v2
        with:
        
          context: ./backend
          
          tags: ${{secrets.DOCKERHUB_USERNAME}}/asi2-ms-card
          
          push: ${{ github.ref == 'refs/heads/main' }}

  push-frontend:
    runs-on: ubuntu-latest
    
    env:
      working-directory: ./client 
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        run: docker login -u ${{secrets.DOCKERHUB_USERNAME }} -p ${{secrets.DOCKERHUB_TOKEN }}


      - name: Build image and push frontend
        uses: docker/build-push-action@v2
        with:
          context: ./client
          tags: ${{secrets.DOCKERHUB_USERNAME}}/asi2-client
          push: ${{ github.ref == 'refs/heads/main' }}
  
  push-proxy:
    runs-on: ubuntu-latest
    
    env:
      working-directory: ./reverseproxy 
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Login to DockerHub
        run: docker login -u ${{secrets.DOCKERHUB_USERNAME }} -p ${{secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push reverseproxy
        uses: docker/build-push-action@v2
        with:
          context: ./reverseproxy
          tags: ${{secrets.DOCKERHUB_USERNAME}}/asi2-reverseproxy
          push: ${{ github.ref == 'refs/heads/main' }}